name = "day-by-day"
pages_build_output_dir = "dist"
compatibility_date = "2026-03-17"

[vars]
APP_ENV = "production"
SESSION_TTL_SECONDS = "2592000"

[[d1_databases]]
binding = "day-by-day"
database_name = "day-by-day"
database_id = "7334c912-7626-4033-8971-ecbd347a1ab3"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "SESSIONS"
id = "e491b4b07d264ca886ccf2e2cc71493f"

[[r2_buckets]]
binding = "day_by_day_photos"
bucket_name = "day-by-day-photos"
